### Criar um Produto (Coca Cola 2L)
POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "barcode": "123412112",
  "name": "Coca Cola 2L"
}

### Criar uma Ordem de Pedido (Fanta Uva 350ml)
POST http://localhost:3000/product-orders HTTP/1.1
Content-Type: application/json

{
  "barcode": "123412112",
  "orderQuantity": 24,
  "orderDate": "2026-05-20T09:00:00Z"
}

### Criar uma Entrada de Pedido (Fanta Uva 350ml)
POST http://localhost:3000/product-inputs HTTP/1.1
Content-Type: application/json

{
  "productOrderId": "01638a32-268c-48ee-8f37-0d658ef4d353",
  "inputQuantity": 24,
  "inputDate": "2026-05-25T19:00:00Z"
}